<?php

namespace Database\Seeders;

use App\Models\Branch;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Branch::insert([
            [
                'company_id' => 1,
                'code' => 'B00001',
                'name' => 'Utomodeck Metal Works',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'description' => 'Description for Branch Head Office',
                'type' => 'Head Office',
                'status' => 'Active',
                'photo' => 'photo1.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00002',
                'name' => 'Utomo Juragan Atap Surya Indonesia (UJASI)',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Distribution',
                'photo' => 'photo2.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00003',
                'name' => 'AMAK Pasukan Katak',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00004',
                'name' => 'USOPATER',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00005',
                'name' => 'UMBI',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00006',
                'name' => 'Utomo Charger Plus',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00007',
                'name' => 'Jurtap Bali',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00008',
                'name' => 'Jurtap Banyuwangi',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00009',
                'name' => 'Jurtap Makasar',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00010',
                'name' => 'Jurtap Bandung',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00011',
                'name' => 'Jurtap Bogor',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00012',
                'name' => 'Jurtap Jateng',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00013',
                'name' => 'Jurtap Jember',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00014',
                'name' => 'Jurtap Kalses',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00015',
                'name' => 'Jurtap Pemalang',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00016',
                'name' => 'Jurtap Purbalingga',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00017',
                'name' => 'Jurtap Solo',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00018',
                'name' => 'Jurtap Sumsel',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code' => 'B00019',
                'name' => 'Jurtap Sumut',
                'database' => 'SIMULASI_NEW_UD',
                'email' => 'info@utomodeck.com',
                'address' => 'Jl. Basuki Rahmat No.149, Embong Kaliasin, Kec. Genteng, Surabaya, Jawa Timur 60271',
                'phone' => '(031) 534 4356',
                'type' => 'Branch Office',
                'status' => 'Active',
                'description' => 'Description for Branch Production',
                'photo' => 'photo3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);
    }
}
